//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class administrateur 
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public administrateur()
        {
            this.administrateur_personne = new HashSet<administrateur_personne>();
        }

        public administrateur(ICollection<administrateur_personne> administrateur_personne)
        {
            this.administrateur_personne = administrateur_personne;
        }

        public administrateur(string personneEmail)
        {
            this.personneEmail = personneEmail;
        }

        public int idAdministrateur { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Adresse Email")]
        [DataType(DataType.EmailAddress)]
        public string personneEmail { get; set; }

        public IEnumerable<personne>perso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<administrateur_personne> administrateur_personne { get; set; }

        public virtual ICollection<personne> personne_email { get; set; }
        public virtual administrateur_evenement administrateur_evenement { get; set; }
        public virtual personne personne { get; set; }
    }
}
