//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carteCredit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public carteCredit()
        {
            this.paiements = new HashSet<paiement>();
            this.remboursements = new HashSet<remboursement>();
        }
    
        public int idCarte { get; set; }
        public int numeroCarte { get; set; }
        public System.DateTime dateExpiration { get; set; }
        public int numeroSecret { get; set; }
        public string nomTitulaire { get; set; }
        public string prenomTitulaire { get; set; }
        public string typeCarte { get; set; }
        public Nullable<System.DateTime> dateSuppression { get; set; }
        public string etat { get; set; }
        public string personneEmail { get; set; }
        public Nullable<int> banqueId { get; set; }
    
        public virtual banque banque { get; set; }
        public virtual personne personne { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paiement> paiements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<remboursement> remboursements { get; set; }
    }
}
