//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class evenement
    {
        

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public evenement()
        {
            this.administrateur_evenement = new HashSet<administrateur_evenement>();
            this.paiements = new HashSet<paiement>();
            this.participant_evenement = new HashSet<participant_evenement>();
        }

        public int idEvenement { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Date de debut")]
        [DataType(DataType.Date)]
        public System.DateTime dateDebut { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Date de fin")]
        [DataType(DataType.Date)]
        public System.DateTime dateFin { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Adresse")]
        public string adresse { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Ville")]
        public string ville { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Province")]
        public string province { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Pays")]
        public string pays { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Code postsal")]
        public string codePostal { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Sport")]
        public string sport { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Like")]
        public decimal prix { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Nombre max des participants")]
        [Range(1,int.MaxValue,ErrorMessage ="seulement les nombre positifs acceptes")]
        public int nombreParticipant { get; set; }
        [Display(Name = " Nombre des participants")]
        public int nombreRejoint { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Heure de debut")]
        [DataType(DataType.Time)]
        public System.TimeSpan heureDebut { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Heure de fin")]
        [DataType(DataType.Time)]
        public System.TimeSpan heureFin { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Type")]
        public string type { get; set; }
        
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Genre")]
        public string genre { get; set; }
        [DataType(DataType.DateTime)]
        public System.DateTime dateCreation { get; set; } = DateTime.Now;
        public Nullable<System.DateTime> dateSuppression { get; set; }

        [Display(Name = " Email")]
        public string personneEmail { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<administrateur_evenement> administrateur_evenement { get; set; }
        public virtual personne personne { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paiement> paiements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<participant_evenement> participant_evenement { get; set; }
    }
}
