//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class mail
    {
        public int idEmail { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire et doit etre en format Mail")]
        [Display(Name = " Adresse Email")]
        [DataType(DataType.EmailAddress)]
        public string emailDestinataire { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Sujet")]
       
        public string sujet { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Votre message")]
        [DataType(DataType.MultilineText)]
        public string contenue { get; set; }
        public System.DateTime dateEnvoie { get; set; }
        public string etat { get; set; }
        public string personneEmail { get; set; }
    
        public virtual personne personne { get; set; }
    }
}
