//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class evEntities1 : DbContext
    {
        public evEntities1()
            : base("name=evEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrateur> administrateurs { get; set; }
        public virtual DbSet<administrateur_evenement> administrateur_evenement { get; set; }
        public virtual DbSet<administrateur_personne> administrateur_personne { get; set; }
        public virtual DbSet<banque> banques { get; set; }
        public virtual DbSet<carteCredit> carteCredits { get; set; }
        public virtual DbSet<evenement> evenements { get; set; }
        public virtual DbSet<mail> mails { get; set; }
        public virtual DbSet<note> notes { get; set; }
        public virtual DbSet<organisateur> organisateurs { get; set; }
        public virtual DbSet<paiement> paiements { get; set; }
        public virtual DbSet<participant> participants { get; set; }
        public virtual DbSet<participant_evenement> participant_evenement { get; set; }
        public virtual DbSet<personne> personnes { get; set; }
        public virtual DbSet<remboursement> remboursements { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
