//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class note
    {
        public note(int note1, int? organisateurId)
        {
            this.note1 = note1;
            this.organisateurId = organisateurId;
        }

        public int idNote { get; set; }
        public int note1 { get; set; }
        public System.DateTime datePublication { get; set; }
        public Nullable<System.DateTime> dateSuppression { get; set; }
        public string etat { get; set; }
        public Nullable<int> participantIdParticipant { get; set; }
        public Nullable<int> organisateurId { get; set; }
    
        public virtual organisateur organisateur { get; set; }
        public virtual participant participant { get; set; }
    }
}
