//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paiement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paiement()
        {
            this.remboursements = new HashSet<remboursement>();
        }
    
        public int idPaiement { get; set; }
        public decimal somme { get; set; }
        public System.DateTime datePaiement { get; set; }
        public string etat { get; set; }
        public Nullable<int> evenementId { get; set; }
        public Nullable<int> carteCreditId { get; set; }
    
        public virtual carteCredit carteCredit { get; set; }
        public virtual evenement evenement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<remboursement> remboursements { get; set; }
    }
}
