//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class participant_evenement
    {
        public participant_evenement(int idParticipant, int evenementId, user user)
        {
            this.IdParticipant = idParticipant;
            this.evenementId = evenementId;
           // this.Identifiant = Identifiant;
        }

        public participant_evenement()
        {
        }

   

        public participant_evenement(int idParticipant, int? id)
        {
            IdParticipant = idParticipant;
            Id = id;
        }

        public participant_evenement(int participantId, int? evenementId, int idUtilisateur )
        {
            this.participantId = participantId;
            this.evenementId = evenementId;
            this.idUtilisateur = idUtilisateur;
            
        }

        public participant_evenement(int participantId, int? evenementId, int idUtilisateur, int note) : this(participantId, evenementId, idUtilisateur)
        {
            this.note = note;
        }

        public int participantId { get; set; }
        public int? evenementId { get; set; }
        public int idUtilisateur { get; set; }
        public int note { get; set; }
        public virtual evenement evenement { get; set; }
        public virtual participant participant { get; set; }
        public virtual user user { get; set; }
        public int IdParticipant { get; }
        public int? Id { get; }
        public int identifiant { get; }

       
    }
}
