//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class participant
    {
        private DateTime now;
        private int idUtilisateur;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public participant()
        {
            this.notes = new HashSet<note>();
            this.organisateurs = new HashSet<organisateur>();
        }
        public participant(DateTime now, int utilisateurIdUtilisateur)
        {
            this.now = now;
            this.utilisateurIdUtilisateur = utilisateurIdUtilisateur;
        }

     

        public int idParticipant { get; set; }
        public System.DateTime dateRejoint { get; set; }
        public Nullable<System.DateTime> dateQuitter { get; set; }
        public int utilisateurIdUtilisateur { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<note> notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<organisateur> organisateurs { get; set; }
        public virtual participant_evenement participant_evenement { get; set; }
        public virtual user user { get; set; }
    }
}
