//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class personne
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personne()
        {
            this.administrateurs = new HashSet<administrateur>();
            this.carteCredits = new HashSet<carteCredit>();
            this.evenements = new HashSet<evenement>();
            this.mails = new HashSet<mail>();
            this.organisateurs = new HashSet<organisateur>();
            this.users = new HashSet<user>();
        }

        public personne(string nom, string prenom, string email, string motDePasse, DateTime dateDeNaissance, string genre, string occupation, DateTime? dateDeCreation)
        {
            this.nom = nom;
            this.prenom = prenom;
            this.email = email;
            this.motDePasse = motDePasse;
            this.dateDeNaissance = dateDeNaissance;
            this.genre = genre;
            this.occupation = occupation;
            DateDeCreation = dateDeCreation;
        }

        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Nom")]
        public string nom { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Prenom")]
        public string prenom { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Adresse Email")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Mot de passe")]
        [DataType(DataType.Password)]
        public string motDePasse { get; set; }

        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Confirmer mot de passe")]
        [DataType(DataType.Password)]
        [Compare("motDePasse", ErrorMessage = "Le mot de passe n'est pas matche")]
        public string RePassword { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Date de naissance")]
        [DataType(DataType.Date)]
        public System.DateTime dateDeNaissance { get; set; }


        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Genre")]
        public string genre { get; set; }
        [Required(ErrorMessage = " ce champs est obligatoire")]
        [Display(Name = " Occupation")]
        public string occupation { get; set; }
        public Nullable<System.DateTime> DateDeCreation { get; set; } = DateTime.Now;
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<administrateur> administrateurs { get; set; }
        public virtual administrateur_personne administrateur_personne { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carteCredit> carteCredits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evenement> evenements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mail> mails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<organisateur> organisateurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
    }
}
