//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remboursement
    {
        public int idRemboursement { get; set; }
        public decimal somme { get; set; }
        public System.DateTime dateRemboursement { get; set; }
        public string etat { get; set; }
        public Nullable<int> paiementId { get; set; }
        public Nullable<int> carteCreditId { get; set; }
    
        public virtual carteCredit carteCredit { get; set; }
        public virtual paiement paiement { get; set; }
    }
}
